// <auto-generated />
namespace DoctorConsult.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class doctorandpatientprofilerequiredremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorandpatientprofilerequiredremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "202009231534204_doctor and patient profile required removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
