// <auto-generated />
namespace DoctorConsult.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class authenticationtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(authenticationtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202009221918201_authentication-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
